/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.qp5;

import java.util.ArrayList;
import javax.swing.AbstractListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author teoberbic
 */


public class UserWindow extends javax.swing.JFrame {

    private class CustomListModel extends AbstractListModel<String> {
        
        private ArrayList<GameItem> items = new ArrayList<GameItem>();
        
        public CustomListModel() {
            super();
        }
        
        @Override
        public int getSize() {
            return items.size();
        }
        
        @Override
        //Gets Item Name
        public String getElementAt(int index) { 
            return items.get(index).getName();
        }
        
        //Gets item Description
        public String getElementAtDesc(int index) {
            return items.get(index).getDescription();
        }
        
        public void addElement(GameItem item){
            items.add(item);
            int t = items.size()-1;
            fireContentsChanged(this, t, t);
        }
        
        public GameItem removeElement(int index){
            if(items.size() > 0){
                GameItem item = items.remove(index);
                fireContentsChanged(this, index, items.size()-1); 
                return item;
            }
            return null;
        }
    }
    
    public UserWindow() {
        initComponents();
        
        //Creates instances in my inventory and room
        CustomListModel myItems = new CustomListModel();
        myItems.items.add(new GameItem("sword", "this item is very sharp and dangerous"));
        myItems.items.add(new GameItem("hammer", "this item can help you build"));
        myItems.items.add(new GameItem("bread", "this item will give you 2 hunger points"));
        myItems.items.add(new GameItem("carrot", "this item will give you 4 hunger points"));
        myItems.items.add(new GameItem("toothpick", "this item will give you spotless teeth"));
        
        CustomListModel roomItems = new CustomListModel();
        roomItems.items.add(new GameItem("apple", "this item will give you one hunger point"));
        roomItems.items.add(new GameItem("seed", "this item you can grow to gain more food"));
        roomItems.items.add(new GameItem("diamond", "this item is extremly precious"));
        roomItems.items.add(new GameItem("wire", "this item is extremly dangerous"));
        roomItems.items.add(new GameItem("shirt", "this item will leave give you a piece of clothing"));
        
        jListMyInventory.setModel(myItems);
        jListRoomInventory.setModel(roomItems);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAdd = new javax.swing.JButton();
        btnDrop = new javax.swing.JButton();
        btnInspect = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListMyInventory = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jListRoomInventory = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnDrop.setText("Drop");
        btnDrop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDropActionPerformed(evt);
            }
        });

        btnInspect.setText("Inspect");
        btnInspect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInspectActionPerformed(evt);
            }
        });

        jListMyInventory.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jListMyInventory);

        jListRoomInventory.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(jListRoomInventory);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAdd)
                        .addGap(71, 71, 71)
                        .addComponent(btnDrop))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnInspect)
                        .addGap(22, 22, 22))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 111, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdd)
                    .addComponent(btnDrop)
                    .addComponent(btnInspect))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        int selectedIndex = jListRoomInventory.getSelectedIndex();
        if (selectedIndex != -1) {
            CustomListModel roomItems = ((CustomListModel)jListRoomInventory.getModel());
            CustomListModel myItems = ((CustomListModel)jListMyInventory.getModel());
            myItems.addElement(roomItems.removeElement(selectedIndex));
        }
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnDropActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDropActionPerformed
        int selected = jListMyInventory.getSelectedIndex();
        if (selected != -1) {
            CustomListModel myItems = ((CustomListModel)jListMyInventory.getModel());
            CustomListModel roomItems = ((CustomListModel)jListRoomInventory.getModel());
            if(myItems.getSize() > 0) {
                roomItems.addElement(myItems.removeElement(selected));
            }
        }
    }//GEN-LAST:event_btnDropActionPerformed

    private void btnInspectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInspectActionPerformed
        int selectedIndex = jListMyInventory.getSelectedIndex();
        if (selectedIndex != -1) {
            CustomListModel myItems = ((CustomListModel)jListMyInventory.getModel());
            String description = myItems.getElementAtDesc(selectedIndex);
            JOptionPane.showMessageDialog(null, description, "Description", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnInspectActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnDrop;
    private javax.swing.JButton btnInspect;
    private javax.swing.JList<String> jListMyInventory;
    private javax.swing.JList<String> jListRoomInventory;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
