/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.javapractice;

import java.awt.HeadlessException;
import java.io.IOException;
import javax.swing.JOptionPane;

/**
 *
 * @author Teo
 */
public class Calculator extends javax.swing.JFrame {
    
    /**
     * Creates new form Calculator
     */
    public Calculator() {
        initComponents();
        this.setResizable(false);
        this.setDefaultCloseOperation(Calculator.DISPOSE_ON_CLOSE);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton3 = new javax.swing.JButton();
        jLabelResult = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButtonOne = new javax.swing.JButton();
        jButtonTwo = new javax.swing.JButton();
        jButtonAdd = new javax.swing.JButton();
        jButtonThree = new javax.swing.JButton();
        jButtonFour = new javax.swing.JButton();
        jButtonSix = new javax.swing.JButton();
        jButtonSeven = new javax.swing.JButton();
        jButtonFive = new javax.swing.JButton();
        jButtonEight = new javax.swing.JButton();
        jButtonNine = new javax.swing.JButton();
        jButtonZero = new javax.swing.JButton();
        jButtonSubtract = new javax.swing.JButton();
        jButtonEquals = new javax.swing.JButton();
        jTextFieldResults = new javax.swing.JTextField();
        jButtonClear = new javax.swing.JButton();
        jButtonDivide = new javax.swing.JButton();
        jButtonDot = new javax.swing.JButton();

        jButton3.setText("jButton3");

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButtonOne.setText("1");
        jButtonOne.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOneActionPerformed(evt);
            }
        });

        jButtonTwo.setText("2");
        jButtonTwo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTwoActionPerformed(evt);
            }
        });

        jButtonAdd.setText("+");
        jButtonAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddActionPerformed(evt);
            }
        });

        jButtonThree.setText("3");
        jButtonThree.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonThreeActionPerformed(evt);
            }
        });

        jButtonFour.setText("4");
        jButtonFour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFourActionPerformed(evt);
            }
        });

        jButtonSix.setText("6");
        jButtonSix.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSixActionPerformed(evt);
            }
        });

        jButtonSeven.setText("7");
        jButtonSeven.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSevenActionPerformed(evt);
            }
        });

        jButtonFive.setText("5");
        jButtonFive.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFiveActionPerformed(evt);
            }
        });

        jButtonEight.setText("8");
        jButtonEight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEightActionPerformed(evt);
            }
        });

        jButtonNine.setText("9");
        jButtonNine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNineActionPerformed(evt);
            }
        });

        jButtonZero.setText("0");
        jButtonZero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonZeroActionPerformed(evt);
            }
        });

        jButtonSubtract.setText("-");
        jButtonSubtract.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSubtractActionPerformed(evt);
            }
        });

        jButtonEquals.setText("=");
        jButtonEquals.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEqualsActionPerformed(evt);
            }
        });

        jTextFieldResults.setEditable(false);

        jButtonClear.setText("Clear");
        jButtonClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonClearActionPerformed(evt);
            }
        });

        jButtonDivide.setText("/");
        jButtonDivide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDivideActionPerformed(evt);
            }
        });

        jButtonDot.setText(".");
        jButtonDot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDotActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldResults)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonOne)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonTwo)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonThree)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonSubtract))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonFour)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonFive)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonSix)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonAdd))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jButtonZero)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonDot)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonEquals))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jButtonSeven)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonEight)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonNine)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jButtonDivide))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButtonClear, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jTextFieldResults, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonOne)
                    .addComponent(jButtonTwo)
                    .addComponent(jButtonThree)
                    .addComponent(jButtonSubtract))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButtonFour)
                        .addComponent(jButtonFive)
                        .addComponent(jButtonSix))
                    .addComponent(jButtonAdd))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonSeven)
                    .addComponent(jButtonEight)
                    .addComponent(jButtonNine)
                    .addComponent(jButtonDivide))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonZero)
                    .addComponent(jButtonDot)
                    .addComponent(jButtonEquals)
                    .addComponent(jButtonClear))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void operationFn(String operation) {
        String text = jTextFieldResults.getText();
        if (text.contains("-") | (text.contains("+")) | (text.contains("/")) | (text.contains("x"))) {
            
        } else {
             jTextFieldResults.setText(jTextFieldResults.getText() + operation);
        }
    }
    private void jButtonOneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOneActionPerformed
        jTextFieldResults.setText(jTextFieldResults.getText() + "1");
    }//GEN-LAST:event_jButtonOneActionPerformed

    private void jButtonAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddActionPerformed
        operationFn("+");
    }//GEN-LAST:event_jButtonAddActionPerformed

    private void jButtonEqualsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEqualsActionPerformed
//        String text = jTextFieldResults.getText();
//        //"(?<=\\d)(?=\\D)|(?<=\\D)(?=\\d)"
//        String[] nums = text.split("(?<=\\d\\.\\d)(?=\\D)|(?<=\\D)(?=\\d\\.\\d)|(?<=\\d)(?=\\D)|(?<=\\D)(?=\\d)");
//        if (nums.length < 3) {
//            return;
//        }
//        Number firstNum = null;
//        try {
//                if (nums[0].contains(".")) {
//                    firstNum = Double.valueOf(nums[0]);
//                } else {
//                    firstNum = Integer.valueOf(nums[0]);
//                }
//                    
//            
//                    
//            
//            int secondNum = Integer.parseInt(nums[2]);      
//            String operator = nums[1];
//            switch(operator) {
//                case "+" -> {
//                    if(firstNum instanceof Double) {
//                        double result = ((Double) firstNum) + secondNum;
//                        String resultStr = String.valueOf(result);
//                        jTextFieldResults.setText(resultStr);
//                    
//                    } else if (firstNum instanceof Integer) {
//                        int result = ((Integer) firstNum) + secondNum;
//                        String resultStr = String.valueOf(result);
//                        jTextFieldResults.setText(resultStr);
//                    }
//                    
//                }
//            }
////                    
////                }
////                case "-" -> {
////                    int result = firstNum - secondNum;
////                    String resultStr = String.valueOf(result);
////                    jTextFieldResults.setText(resultStr);
////                }
////                case "/" -> {
////                    int result = firstNum / secondNum;
////                    String resultStr = String.valueOf(result);
////                    jTextFieldResults.setText(resultStr);
////                }
////            }
//                
//        } catch (NumberFormatException t) {
//            JOptionPane.showMessageDialog(null, "NUMBER TOO HIGH", "NUMBER LIMIT EXCEEDED", JOptionPane.ERROR_MESSAGE);
//            jTextFieldResults.setText("");
//        }
          String text = jTextFieldResults.getText();
          //"(?<=\\d)(?=\\D)|(?<=\\D)(?=\\d)"
          String[] nums = text.split("(?<=\\d)(?=[+\\-*/])|(?<=[+\\-*/])(?=\\d)");
          if (nums.length < 3) {
             return;
          }
          jTextFieldResults.setText(nums[1]);
            try {
                    double firstNum = Double.parseDouble(nums[0]);
                    double secondNum = Double.parseDouble(nums[2]);      
                    String operator = nums[1];
                   
                    switch(operator) {
                        case "+" -> {
                            double result = firstNum + secondNum;
                            String resultStr = String.valueOf(result);
                            jTextFieldResults.setText(resultStr);
                            break;
                        }
                        case "-" -> {
                            double result = firstNum - secondNum;
                            String resultStr = String.valueOf(result);
                            jTextFieldResults.setText(resultStr);
                            break;
                        }
                        case "/" -> {
                            double result = firstNum / secondNum;
                            String resultStr = String.valueOf(result);
                            jTextFieldResults.setText(resultStr);
                            break;
                        }
                        
                    }
                
            } catch (NumberFormatException t) {
                JOptionPane.showMessageDialog(null, "NUMBER TOO HIGH", "NUMBER LIMIT EXCEEDED", JOptionPane.ERROR_MESSAGE);
                jTextFieldResults.setText("");
            } catch (HeadlessException e) {
                jTextFieldResults.setText("");
            }
      
      
      
    }//GEN-LAST:event_jButtonEqualsActionPerformed

    private void jButtonSubtractActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSubtractActionPerformed
        operationFn("-");
    }//GEN-LAST:event_jButtonSubtractActionPerformed

    private void jButtonClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonClearActionPerformed
        jTextFieldResults.setText("");
    }//GEN-LAST:event_jButtonClearActionPerformed

    private void jButtonTwoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTwoActionPerformed
        jTextFieldResults.setText(jTextFieldResults.getText() + "2");
    }//GEN-LAST:event_jButtonTwoActionPerformed

    private void jButtonThreeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonThreeActionPerformed
        jTextFieldResults.setText(jTextFieldResults.getText() + "3");
    }//GEN-LAST:event_jButtonThreeActionPerformed

    private void jButtonFourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFourActionPerformed
        jTextFieldResults.setText(jTextFieldResults.getText() + "4");
    }//GEN-LAST:event_jButtonFourActionPerformed

    private void jButtonFiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFiveActionPerformed
        jTextFieldResults.setText(jTextFieldResults.getText() + "5");
    }//GEN-LAST:event_jButtonFiveActionPerformed

    private void jButtonSixActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSixActionPerformed
        jTextFieldResults.setText(jTextFieldResults.getText() + "6");
    }//GEN-LAST:event_jButtonSixActionPerformed

    private void jButtonSevenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSevenActionPerformed
        jTextFieldResults.setText(jTextFieldResults.getText() + "7");
    }//GEN-LAST:event_jButtonSevenActionPerformed

    private void jButtonEightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEightActionPerformed
        jTextFieldResults.setText(jTextFieldResults.getText() + "8");
    }//GEN-LAST:event_jButtonEightActionPerformed

    private void jButtonNineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNineActionPerformed
        jTextFieldResults.setText(jTextFieldResults.getText() + "9");
    }//GEN-LAST:event_jButtonNineActionPerformed

    private void jButtonZeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonZeroActionPerformed
        jTextFieldResults.setText(jTextFieldResults.getText() + "0");
    }//GEN-LAST:event_jButtonZeroActionPerformed

    private void jButtonDivideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDivideActionPerformed
       operationFn("/");
    }//GEN-LAST:event_jButtonDivideActionPerformed

    private void jButtonDotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDotActionPerformed
        String text = jTextFieldResults.getText();
        int dotCounter = 0;
        for(int i =0; i < text.length(); i++) {
            if (text.charAt(i) == '.') {
                dotCounter++;
            }
        }
        if (dotCounter >= 2) {
            return;   
        }
        
        jTextFieldResults.setText(jTextFieldResults.getText() + '.');
       
    }//GEN-LAST:event_jButtonDotActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButtonAdd;
    private javax.swing.JButton jButtonClear;
    private javax.swing.JButton jButtonDivide;
    private javax.swing.JButton jButtonDot;
    private javax.swing.JButton jButtonEight;
    private javax.swing.JButton jButtonEquals;
    private javax.swing.JButton jButtonFive;
    private javax.swing.JButton jButtonFour;
    private javax.swing.JButton jButtonNine;
    private javax.swing.JButton jButtonOne;
    private javax.swing.JButton jButtonSeven;
    private javax.swing.JButton jButtonSix;
    private javax.swing.JButton jButtonSubtract;
    private javax.swing.JButton jButtonThree;
    private javax.swing.JButton jButtonTwo;
    private javax.swing.JButton jButtonZero;
    private javax.swing.JLabel jLabelResult;
    private javax.swing.JTextField jTextFieldResults;
    // End of variables declaration//GEN-END:variables
}
